spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atm
    username: admin
    password: 1
  jpa:
    properties:
      hibernate:
        show_format: true
    #        show_sql: true
    #        generate_statistics: true
    hibernate:
      ddl-auto: update



server:
  port: 8585
  error:
    include-message: always

  servlet:
    context-path: /api

